language: node_js
node_js:
    - "lts/*"
sudo: required

addons:
  chrome: stable

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - npm install -g gulp-cli
script:
    - gulp build
    - gulp test-unit
